config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'items/edit'
resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	@items = Item.all
  end

  def new
  	@item = Item.new
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def show
  	@item = Item.find(params[:id])
  end

  def create
  	@item = Item.new(item_params)

  		if @item.save
  			redirect_to items_path
  		else
  			render :new
  		end
  end

	def update
  	@item = Item.find(params[:id])

  		if @item.update(item_params)
  			redirect_to items_path
  		else
  			render :edit
  		end
  end
  
  def destroy
  	Item.find(params[:id]).destroy
  	redirect_to items_path
  end

  private

  def item_params
  	params.require(:item).permit(:name, :description, :completed)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/items/edit.html.erb
<h1>Edit Item</h1>
<%= form_for @item do |f| %>
	<%= f.label :name %>:
	<%= f.text_field :name %>

	<%= f.label :description %>
	<%= f.text_field :description %>
	
	<%= f.label :completed %>	
	<%= f.check_box :completed %>


	<%= f.submit %>
	<% end %>

app/views/items/index.html.erb
<h1>To Do:</h1>
<% @items.each do |item| %>
	<h2><%= item.name %></h2>
	<p><%= item.description %></p>
	<p>completed? <%= item.completed %></p>
	<%= link_to 'Edit Item', edit_item_path(item) %>
	<%= link_to 'Delete Item', item, method: :delete %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%=form_for @item do |f| %>
	<%= f.label :name %>:
	<%= f.text_field :name %>

	<%= f.label :description %>
	<%= f.text_field :description %>

	<%= f.submit %>
	<%= link_to 'Back', items_path %> 
<% end %>

app/views/items/show.html.erb
<h1>Item</h1>
<h2><%= @item.name %></h2>
<h3><%= @item.description %></h3>
<h4><%= @item.completed %></h4>
<%= link_to 'Back', items_path %> 

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %> |
<%= link_to 'Honey-Do List', items_path %> |
<%= link_to 'New Item', new_item_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>Fort Garcia</h1>
<p>Taking care of Home</p>
<p>**Coming soon**</p>
<p> A new way to incentivize couch potatoes//</p>